### PR TITLE
Update for Sonic Mania 1.03.0919

### PR DESCRIPTION
**Pull request by thesupersonic16**
Sorry for converting some tabs to spaces.

### CODE REVIEW

**Comment by Araraura** [comment]
How do I download this?

**Comment by MainMemory** [comment]
@Araraura From the Releases tab on his repository.

**Comment by MainMemory** [comment]
I appreciate all the work you've put into this, but I don't know if I'm comfortable with just merging your changes into the main branch, because it would make the history complicated, with lines being deleted and re-added, tabs being converted to spaces, etc.

I may just use your fork as a reference, and perform the update myself all at once.

**Comment by thesupersonic16** [comment]
ok, Gonna close the PR, I'll will also update my fork with changes i feel should be in. I hope you use my `codes.xml` file as It will be a huge pain if you don't.

**Comment by MainMemory** [comment]
Well, if you have additional codes, I may add them, or you could submit them as a pull request when I've done the upgrade.

**Comment by thesupersonic16** [comment]
The `codes.xml` in my repo should work, I spent a huge amount of time updating that file. :)

**Comment by thesupersonic16** [comment]
And if i do have more codes I'll try make a PR maybe on another branch to keep it cleaner

**Pull request closed without merging**
